wandb_version: 1

model_name:
  desc: null
  value: VanillaTransformer
data_path:
  desc: null
  value: data/shakespeare/tinyshakespeare_100_lines.txt
chunk_size:
  desc: null
  value: 50
max_seq_length:
  desc: null
  value: 25
nhead:
  desc: null
  value: 2
dim_feedforward:
  desc: null
  value: 1024
dmodel:
  desc: null
  value: 256
dropout:
  desc: null
  value: 0.1
split_ratio:
  desc: null
  value: 0.8
window_step_size:
  desc: null
  value: 25
batch_size:
  desc: null
  value: 16
num_epochs:
  desc: null
  value: 2
lr:
  desc: null
  value: 0.001
nembd:
  desc: null
  value: 768
num_layers:
  desc: null
  value: 2
block_size:
  desc: null
  value: 1024
max_iters:
  desc: null
  value: 0.0
recurrent_layers:
  desc: null
  value: all
distributed:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.34.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702076385.506538
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 105
      2:
      - 1
      - 11
      - 49
      - 55
      - 105
      3:
      - 7
      - 16
      - 23
      4: 3.11.0
      5: 0.16.1
      6: 4.34.1
      8:
      - 3
      - 5
      13: windows-amd64
    m:
    - 1: epoch
      6:
      - 3
